[project]
name = "hyprwyn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hyprpy>=0.2.0",
    "loguru>=0.7.3",
    "rich>=14.1.0",
]
